from agents.base_agent import BaseAgent
from style_swapper.presets import COLOR_PRESETS, DEFAULT_VARIANT, STYLE_VARIANTS


class StylingAgent(BaseAgent):
    """
    Runs after the Component Agent. Its two jobs:
    1. Emit a global index.css with CSS custom properties for the chosen
       theme, so hand-written and generated code share one source of truth.
    2. Tag every generated component with the preset it was styled around,
       which is exactly the metadata the Style Swapper needs later to do
       instant, targeted color replacement instead of a blind find/replace.
    This agent is deterministic (no LLM call) because theme bookkeeping is
    mechanical — the LLM's creative work already happened in the Component
    Agent's prompt, which was told which palette to use.
    """

    name = "Styling Agent"

    def build_global_css(self, theme_name: str) -> str:
        palette = COLOR_PRESETS.get(theme_name, COLOR_PRESETS["Ocean Blue"])
        return f"""@tailwind base;
@tailwind components;
@tailwind utilities;

/* Generated by the Styling Agent for theme: {theme_name} */
:root {{
  --color-primary: theme('colors.{palette["primary"]}.500');
  --color-secondary: theme('colors.{palette["secondary"]}.500');
  --color-accent: theme('colors.{palette["accent"]}.500');
  --color-neutral: theme('colors.{palette["neutral"]}.500');
}}

body {{
  @apply antialiased;
}}
"""

    @staticmethod
    def tag_component(component_name: str, theme_name: str) -> dict:
        return {
            "component": component_name,
            "preset": theme_name,
            "variant": DEFAULT_VARIANT,
        }

    @staticmethod
    def available_presets() -> list:
        return list(COLOR_PRESETS.keys())

    @staticmethod
    def available_variants() -> list:
        return list(STYLE_VARIANTS.keys())
